export default {
  LOAD_SETTINGS: 'LOAD_SETTINGS',
  CREATE_PORTFOLIO_FILTERS: 'CREATE_PORTFOLIO_FILTERS',
  DELETE_PORTFOLIO_FILTERS: 'DELETE_PORTFOLIO_FILTERS',
  UPDATE_PORTFOLIO_FILTER_VALUE: 'UPDATE_PORTFOLIO_FILTER_VALUE',
  SELECT_ACCOUNT: 'SELECT_ACCOUNT'
}
