export default {
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  LOAD_SETTINGS: 'LOAD_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CREATE_PORTFOLIO_FILTERS: 'CREATE_PORTFOLIO_FILTERS',
  DELETE_PORTFOLIO_FILTERS: 'DELETE_PORTFOLIO_FILTERS',
  UPDATE_PORTFOLIO_FILTER_VALUE: 'UPDATE_PORTFOLIO_FILTER_VALUE'
}
