export default {
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR',
  LOAD_SETTINGS: 'LOAD_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CREATE_PORTFOLIO_FILTERS: 'CREATE_PORTFOLIO_FILTERS',
  DELETE_PORTFOLIO_FILTERS: 'DELETE_PORTFOLIO_FILTERS',
  UPDATE_PORTFOLIO_FILTER_VALUE: 'UPDATE_PORTFOLIO_FILTER_VALUE'
}
