export default {
  CREATE_MARKET_VALUE: 'CREATE_MARKET_VALUE',
  UPDATE_MARKET_VALUE: 'UPDATE_MARKET_VALUE',
  DELETE_MARKET_VALUES: 'DELETE_MARKET_VALUES',
  LOAD_MARKET_VALUES: 'LOAD_MARKET_VALUES'
}
