export default {
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  GROUP_BY_INSTITUTION: 'GROUP_BY_INSTITUTION',
  CREATE_ACCOUNT_GROUP: 'CREATE_ACCOUNT_GROUP',
  UPDATE_ACCOUNT_GROUP: 'UPDATE_ACCOUNT_GROUP'
}
