export default {
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  UPDATE_INSTITUTION_DATA: 'UPDATE_INSTITUTION_DATA'
}
