export default {
  LOAD_ACCOUNTS: 'LOAD_ACCOUNTS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  UPDATE_GROUPS_BY_INSTITUTION: 'UPDATE_GROUPS_BY_INSTITUTION',
  CREATE_ACCOUNT_GROUP: 'CREATE_ACCOUNT_GROUP'
}
