export default {
  LOAD_TRANSACTIONS: 'LOAD_TRANSACTIONS',
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  ADD_TRANSACTIONS: 'ADD_TRANSACTIONS',
  DELETE_TRANSACTIONS: 'DELETE_TRANSACTIONS',
  UPDATE_SORT_BY: 'UPDATE_SORT_BY'
}
