export default {
  LOAD_TRANSACTIONS: 'LOAD_TRANSACTIONS',
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  UPATE_TRANSACTION_FIELD_IF_MATCHED: 'UPATE_TRANSACTION_FIELD_IF_MATCHED',
  ADD_TRANSACTIONS: 'ADD_TRANSACTIONS',
  DELETE_TRANSACTIONS: 'DELETE_TRANSACTIONS',
  APPLY_EXACT_RULE: 'APPLY_EXACT_RULE'
}
