export default {
  LOAD_TRANSACTIONS: 'LOAD_TRANSACTIONS',
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  ADD_TRANSACTIONS: 'ADD_TRANSACTIONS',
  DELETE_TRANSACTIONS: 'DELETE_TRANSACTIONS',
  CREATE_EXACT_RULE: 'CREATE_EXACT_RULE',
  DELETE_EXACT_RULE: 'DELETE_EXACT_RULE',
  APPLY_EXACT_RULE: 'APPLY_EXACT_RULE'
}
