export default {
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_HANDLE_LOGIN: 'USER_HANDLE_LOGIN',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR'
}
