export default {
  UPDATE_LOGIN_DATA: 'UPDATE_LOGIN_DATA',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR'
}
