export default {
  LOAD_USER_DATA: 'LOAD_USER_DATA',
  LOAD_USER_DATA_SUCCESS: 'LOAD_USER_DATA_SUCCESS',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR'
}
