export default {
  LOAD_BUDGET: 'LOAD_BUDGET',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  CREATE_EXACT_RULE: 'CREATE_EXACT_RULE',
  DELETE_EXACT_RULE: 'DELETE_EXACT_RULE',
  COUNT_RULE_USAGE: 'COUNT_RULE_USAGE',
  RESET_COLOURS: 'RESET_COLOURS'
}
