export default {
  CREATE_EXCHANGE_RATE: 'CREATE_EXCHANGE_RATE',
  UPDATE_EXCHANGE_RATE: 'UPDATE_EXCHANGE_RATE',
  DELETE_CURRENCIES: 'DELETE_CURRENCIES',
  LOAD_EXCHANGE_RATES: 'LOAD_EXCHANGE_RATES'
}
